language: node_js
node_js:
  - 10
before_script:
  - npm i -g @angular/cli@8.3.21
  - npm i
script: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless --code-coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
